import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Amir",
      email: "amiradmin@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
      isSeller: true,
    },
    {
      name: "Tems",
      email: "customer@example.com",
      password: bcrypt.hashSync("4321", 8),
      isAdmin: false,
      isSeller: false,
    },
  ],

  products: [
    {
      name: "Asus ZenBook Pro Duo",
      category: "Electronics",
      image: "/uploads/p1.jpg",
      price: 899.49,
      countInStock: 15,
      brand: "Asus",
      rating: 0,
      numReviews: 0,
      description:
        "Asus ZenBook Pro Duo UX581 15.6inch 4K UHD NanoEdge Bezel Touch, Intel Core i9-9980HK, 32GB RAM, 1TB PCIe SSD, GeForce RTX 2060",
    },
    {
      name: "ASUS UX534FTC",
      category: "Electronics",
      image: "/uploads/p2.jpg",
      price: 1299.09,
      countInStock: 13,
      brand: "Asus",
      rating: 0,
      numReviews: 0,
      description:
        "ASUS UX534FTC-AS77 ZenBook 15 Laptop, 15.6” UHD 4K NanoEdge Display, Intel Core i7-10510U, GeForce GTX 1650, 16GB, 512GB PCIe SSD, ScreenPad 2.0, Amazon Alexa Compatible, Windows 10, Icicle Silver",
    },
    {
      name: "ASUS ROG Strix Scar 15 (2020)",
      category: "Electronics",
      image: "/uploads/p3.jpg",
      price: 799.59,
      countInStock: 23,
      brand: "Asus",
      rating: 0,
      numReviews: 0,
      description:
        "ASUS ROG Strix Scar 15 (2020) Gaming Laptop, 15.6” 240Hz IPS Type FHD, NVIDIA GeForce RTX 2070 Super, Intel Core i7-10875H, 16GB DDR4, 1TB PCIe NVMe SSD, Per-Key RGB KB, Windows 10, G532LWS-DS76",
    },
    {
      name: "Acer Predator Helios",
      category: "Electronics",
      image: "/uploads/p4.jpg",
      price: 1325.29,
      countInStock: 24,
      brand: "Acer",
      rating: 0,
      numReviews: 0,
      description:
        "Acer Predator Helios 300 Gaming Laptop, Intel i7-10750H, NVIDIA GeForce RTX 2060 6GB",
    },
    {
      name: "HP Pavilion Gaming",
      category: "Electronics",
      image: "/uploads/p5.jpg",
      price: 799.25,
      countInStock: 51,
      brand: "HP",
      rating: 0,
      numReviews: 0,
      description:
        "HP Pavilion Gaming 15-Inch Micro-EDGE Laptop, Intel Core i5-9300H Processor, NVIDIA GeForce GTX 1650 4GB",
    },
    {
      name: "ASUS TUF Gaming 27inch 2K HDR Gaming Monitor",
      category: "Electronics",
      image: "/uploads/p6.jpg",
      price: 659.46,
      countInStock: 0,
      brand: "Asus",
      rating: 0,
      numReviews: 0,
      description:
        "ASUS TUF Gaming 27inch 2K HDR Gaming Monitor (VG27AQ) - WQHD (2560 x 1440), 165Hz (Supports 144Hz), 1ms, Extreme Low Motion Blur",
    },
    {
      name: "Acer Nitro 5",
      category: "Electronics",
      image: "/uploads/p7.jpg",
      price: 875.05,
      countInStock: 0,
      brand: "Acer",
      rating: 0,
      numReviews: 0,
      description:
        "Acer Nitro 5 Gaming Laptop, 9th Gen Intel Core i5-9300H, NVIDIA GeForce GTX 1650, 15.6",
    },

    {
      name: "GE Forcce RTX 2080",
      category: "Gaming",
      image: "/uploads/p8.jpg",
      price: 1249.05,
      countInStock: 0,
      brand: "Nvidia",
      rating: 0,
      numReviews: 0,
      description:
        "GeForce RTXTM graphics cards are powered by the Turing GPU architecture and the all-new RTX platform. This gives you up to 6X the performance of previous-generation graphics cards and brings the power of real-time ray tracing and AI to games",
    },

    {
      name: "Razer FHD 144hz",
      category: "Gaming",
      image: "/uploads/p9.jpg",
      price: 1249.05,
      countInStock: 0,
      brand: "Nvidia",
      rating: 0,
      numReviews: 0,
      description:
        "Just when you thought a gaming laptop couldn’t be any more beastly—introducing the new Razer Blade 15, now available with the latest 12th Gen Intel® Core™ processor (14-core) and NVIDIA® GeForce RTX™ 30 Series Laptop GPUs for the most powerful gaming laptop graphics ever. With your choice of a Full HD 360Hz, QHD 240Hz (G-SYNC), or new UHD 144Hz display, enjoy unrivalled performance packed into the thinnest 15” RTX gaming laptop chassis ever.",
    },

    {
      name: "Nike Polo Shirt",
      category: "Shirts",
      image: "/uploads/p10.jpg",
      price: 100,
      countInStock: 15,
      brand: "Nike",
      rating: 0,
      numReviews: 0,
      description: "Nike White Polo shirt",
    },
    {
      name: "Under Armour Shirt",
      category: "Electronics",
      image: "/uploads/p11.jpg",
      price: 120,
      countInStock: 13,
      brand: "Under Armour",
      rating: 0,
      numReviews: 0,
      description: "Under Armour Polo",
    },
    {
      name: "Adidas Stripe Shirt",
      category: "Shirts",
      image: "/uploads/p12.jpg",
      price: 140,
      countInStock: 23,
      brand: "Adidas",
      rating: 0,
      numReviews: 0,
      description: "Adidas Stripe Polo shirt",
    },
    {
      name: "Nike Slack pants",
      category: "Pants",
      image: "/uploads/p13.jpg",
      price: 125,
      countInStock: 24,
      brand: "Nike",
      rating: 0,
      numReviews: 0,
      description: "Formal Slack Pants ",
    },
    {
      name: "Under Armour Formal pants",
      category: "Pants",
      image: "/uploads/p14.jpg",
      price: 155,
      countInStock: 51,
      brand: "Under Armour",
      rating: 0,
      numReviews: 0,
      description: "Premium Slack Pants ",
    },
    {
      name: "Adidas Premium Pants",
      category: "Pants",
      image: "/uploads/p15.jpg",
      price: 150,
      countInStock: 0,
      brand: "Under Armour",
      rating: 0,
      numReviews: 0,
      description: "Adidas Premium Slack Pants ",
    },
  ],
};

export default data;
